---
abstract: 'Get information on arbitrary processes in Windows NT'
author:
  - 'Tom Wyant (wyant at cpan dot org)'
build_requires:
  Test::More: '0.88'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Win32-Process-Info
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Win32::Process::Info:
    file: lib/Win32/Process/Info.pm
    version: '1.021'
  Win32::Process::Info::NT:
    file: lib/Win32/Process/Info/NT.pm
    version: '1.021'
  Win32::Process::Info::PT:
    file: lib/Win32/Process/Info/PT.pm
    version: '1.021'
  Win32::Process::Info::WMI:
    file: lib/Win32/Process/Info/WMI.pm
    version: '1.021'
requires:
  Carp: '0'
  File::Spec: '0'
  Time::Local: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Win32-Process-Info
  license: http://dev.perl.org/licenses/
version: '1.021'
